# Site settings
title: Gregorio Nastasi - personal blog
author:
  name: Gregorio Nastasi
  email: gregorionastasi1@gmail.com
description: "WIP."

nav:
  - title: Home
    url: /
  - title: About
    url: /newpage.html

# Build settings
remote_theme: jekyll/minima
