# Site settings
title: Gregorio Nastasi - personal blog
author:
  name: Gregorio Nastasi
  email: gregorionastasi1@gmail.com
description: "WIP."

nav_pages:
    - about.md

# Build settings
remote_theme: jekyll/minima
