# Site settings
title: Gregorio Nastasi - personal blog
author:
  name: Gregorio Nastasi
  email: gregorionastasi1@gmail.com
description: "WIP."

just_the_docs:
  collections:
    pages:
      output: true
      permalink: /:path/

# Build settings
theme: just-the-docs
